# Welcome to Jekyll!

########### Global Variables ###########
title: 'Yelloadwise: Smart ad network agency'
email: technical.yelloadwise@gmail.com
description: >-
  Yelloadwise, by dominating a great extent of digital media network and giving various advertising campaigns, is capable of meeting the expectation of the most valuable brands. Additionally, by showing the advertisements to the subscribers in a smart way, we bring a long- lasting and remarkable revenue without any damage to media owners’ practical experience.
baseurl: '' # the subpath of your site, e.g. /docs
url: 'https://yelloadwise.ir'
twitter_username:
github_username: tapsellorg
site_name: Yelloadwise
global_vars:
  landing_url: https://irancell.ir
  dashboard_url: https://dashboard.irancell.ir/
  blog_url: https://college.irancell.ir/
  docs_url: https://docs.tapsell.ir/
  site_name: irancell.ir
  get_demo_url: https://dashboard.irancell.ir/
  header_logo_alt: Yelloadwise Docs
  terms_url: https://docs.irancell.ir/terms-and-condition/
  paying_income_url: https://docs.irancell.ir/paying-income/
  faq_url: https://docs.irancell.ir/faq/
  faq_advertisers_url: https://docs.irancell.ir/faq/advertiser/
  contact_email: info@irancell.ir
  footer_logo_alt: Yelloadwise

########### Condfigurations ###########

# Jekyll Configurations: https://jekyllrb.com/docs/configuration/options/
source: src/jekyll

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  parse_block_html: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

plugins:
  - jekyll-seo-tag
  - jekyll-polyglot
  - jekyll-toc

# jekyll-polyglot settings
languages: ['en', 'fa']
default_lang: 'fa'
exclude_from_localizations: ['javascript', 'images', 'css']
parallel_localization: true

# jekyll-minifier settings
jekyll-minifier:
  exclude: 'feed.xml'
  uglifier_args:
    harmony: true

########### Translations ###########
t:
  en:
    nav:
      home: Home
      dashboard: Dashboard
      get_demo: Get a Demo
      blog: Blog
      switch_lang: فارسی
    footer:
      terms: Terms of Service
      contact: Contact Us
      copyright: Designed and Developed by Yelloadwise - Iran
  fa:
    nav:
      home: خانه
      dashboard: داشبورد
      get_demo: دریافت دمو
      blog: کالج یلوادوایز
      switch_lang: English
    footer:
      terms: قوانین و ضوابط
      contact: تماس با ما
      faq_advertisers: سوالات متداول تبلیغ‌دهندگان
      faq: سوالات متداول
      paying_income: پرداخت درآمد
      copyright: طراحی و توسعه توسط یلوادوایز - ایران
